name: Continous Integration Workflow

on:
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  enforce_style:
    name: Enforce style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prettier code style check
        uses: actionsx/prettier@v2
        with:
          args: --check .
